if(EXISTS "/Users/ericzhou/Desktop/Productivity/Projects/Serious/MatchingEngine/build-release/parser_tests[1]_tests.cmake")
  include("/Users/ericzhou/Desktop/Productivity/Projects/Serious/MatchingEngine/build-release/parser_tests[1]_tests.cmake")
else()
  add_test(parser_tests_NOT_BUILT parser_tests_NOT_BUILT)
endif()
